// <auto-generated />
using System;
using INDIA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INDIA.Migrations
{
    [DbContext(typeof(IndiaDbContext))]
    [Migration("20240715080233_Data seeding for the District and Language model")]
    partial class DataseedingfortheDistrictandLanguagemodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INDIA.Models.Domain.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AreaInSqrKm")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47a5276e-5ae0-4c5f-982a-638a5aba10d5"),
                            AreaInSqrKm = 19829.0,
                            Code = "STRA",
                            DistrictImageUrl = "satara/patan.jpeg",
                            Name = "Satara"
                        },
                        new
                        {
                            Id = new Guid("04da054a-fe7f-4961-bb72-5342c389bae7"),
                            AreaInSqrKm = 17293.0,
                            Code = "SNGL",
                            DistrictImageUrl = "sangali/faui.png",
                            Name = "Sangali"
                        },
                        new
                        {
                            Id = new Guid("02c0ee3c-0734-4bd8-aee0-c891cffaa6d4"),
                            AreaInSqrKm = 19999.0,
                            Code = "PNQ",
                            DistrictImageUrl = "pune/baner.jpg",
                            Name = "Pune"
                        },
                        new
                        {
                            Id = new Guid("05536da6-f49d-4dab-80fe-567597c047d8"),
                            AreaInSqrKm = 17899.0,
                            Code = "KLPR",
                            Name = "Kolhapur"
                        });
                });

            modelBuilder.Entity("INDIA.Models.Domain.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07a4c903-83c1-4d51-8398-94a9ca8905a3"),
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = new Guid("77b4897f-5aaf-47b2-9404-6b7b2e60760a"),
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = new Guid("64b3bf89-e50f-4297-919a-36194660c9fc"),
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = new Guid("1c47dbde-52d9-497d-9f9b-9ccb2cc28dfa"),
                            Name = "Telugu"
                        },
                        new
                        {
                            Id = new Guid("5d5992b3-55a4-48ec-b18f-2f9ef4544614"),
                            Name = "Kannada"
                        });
                });

            modelBuilder.Entity("INDIA.Models.Domain.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AreaInSqrKm")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("LanguageId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("INDIA.Models.Domain.State", b =>
                {
                    b.HasOne("INDIA.Models.Domain.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INDIA.Models.Domain.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
